// Originated from aras-p/UnityGaussianSplatting by Aras Pranckevičius
// https://github.com/aras-p/UnityGaussianSplatting/blob/main/package/Shaders/SplatUtilities.compute
// Copyright (c) 2023 Aras Pranckevičius
// Modified by Yize Wu
// Copyright (c) 2025 Yize Wu
// SPDX-License-Identifier: MIT

#define GROUP_SIZE 1024

// DeviceRadixSort
#define KEY_FLOAT
#define PAYLOAD_UINT
#define SHOULD_ASCEND
#define SORT_PAIRS
#pragma multi_compile __ VULKAN

#pragma kernel InitPayload
#pragma kernel InitDeviceRadixSort
#pragma kernel Upsweep
#pragma kernel Scan
#pragma kernel Downsweep
#pragma kernel UpsweepDynamic GSPLAT_DYNAMIC_COUNT
#pragma kernel ScanDynamic GSPLAT_DYNAMIC_COUNT
#pragma kernel DownsweepDynamic GSPLAT_DYNAMIC_COUNT

// GPU sorting needs wave ops
#pragma require wavebasic
#pragma require waveballot
#pragma use_dxc

#include "DeviceRadixSort.hlsl"

[numthreads(GROUP_SIZE,1,1)]
void InitPayload(uint3 id : SV_DispatchThreadID)
{
    uint idx = id.x;
    if (idx >= NumKeys())
        return;

    b_sortPayload[idx] = idx;
}

[numthreads(US_DIM, 1, 1)]
void Upsweep(uint3 gtid : SV_GroupThreadID, uint3 gid : SV_GroupID)
{
    UpsweepImpl(gtid, gid);
}

[numthreads(SCAN_DIM, 1, 1)]
void Scan(uint3 gtid : SV_GroupThreadID, uint3 gid : SV_GroupID)
{
    ScanImpl(gtid, gid);
}

[numthreads(D_DIM, 1, 1)]
void Downsweep(uint3 gtid : SV_GroupThreadID, uint3 gid : SV_GroupID)
{
    DownsweepImpl(gtid, gid);
}

[numthreads(US_DIM, 1, 1)]
void UpsweepDynamic(uint3 gtid : SV_GroupThreadID, uint3 gid : SV_GroupID)
{
    UpsweepImpl(gtid, gid);
}

[numthreads(SCAN_DIM, 1, 1)]
void ScanDynamic(uint3 gtid : SV_GroupThreadID, uint3 gid : SV_GroupID)
{
    ScanImpl(gtid, gid);
}

[numthreads(D_DIM, 1, 1)]
void DownsweepDynamic(uint3 gtid : SV_GroupThreadID, uint3 gid : SV_GroupID)
{
    DownsweepImpl(gtid, gid);
}
